package com.example.ingredientinsight.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

public class IngredientAnalyzer {

    public static class AnalysisResult {
        public int healthScore;
        public String healthLabel;
        public String explanation;
        public List<String> flaggedIngredients = new ArrayList<>();
    }

    private static class Rule {
        final String keyword;
        final int severity;      //negative = bad, positive = good
        final String category;   //Examples are "Added sugar", "Refined grains", etc.
        final String message;    //explanation

        Rule(String keyword, int severity, String category, String message) {
            this.keyword = keyword;
            this.severity = severity;
            this.category = category;
            this.message = message;
        }
    }

    private static final List<Rule> RULES = new ArrayList<>();

    //Add a rule to the list
    private static void addRule(String keyword, int severity, String category, String message) {
        RULES.add(new Rule(keyword, severity, category, message));
    }

    //All engine rules and weights (generated by ChatGPT)
    static {
        // Added sugars
        addRule("sugar", -3, "Added sugar",
                "Contains added sugar");
        addRule("high fructose corn syrup", -4, "Added sugar",
                "Contains high fructose corn syrup");
        addRule("corn syrup", -3, "Added sugar",
                "Contains corn syrup");
        addRule("glucose", -2, "Added sugar",
                "Contains added sugars (glucose)");
        addRule("fructose", -2, "Added sugar",
                "Contains added sugars (fructose)");
        addRule("dextrose", -2, "Added sugar",
                "Contains added sugars (dextrose)");
        addRule("maltose", -2, "Added sugar",
                "Contains added sugars (maltose)");
        addRule("molasses", -2, "Added sugar",
                "Contains added sugars (molasses)");
        addRule("honey", -1, "Added sugar",
                "Contains added sugars (honey)");

        // Refined flours
        addRule("enriched wheat flour", -3, "Refined grains",
                "Contains refined flour");
        addRule("wheat flour", -2, "Refined grains",
                "Contains refined wheat flour");
        addRule("white flour", -3, "Refined grains",
                "Contains white refined flour");

        // Refined/seed oils
        addRule("soybean oil", -3, "Refined oils",
                "Contains refined seed oils (soybean oil)");
        addRule("canola oil", -2, "Refined oils",
                "Contains refined seed oils (canola oil)");
        addRule("corn oil", -2, "Refined oils",
                "Contains refined seed oils (corn oil)");
        addRule("sunflower oil", -2, "Refined oils",
                "Contains refined seed oils (sunflower oil)");
        addRule("cottonseed oil", -3, "Refined oils",
                "Contains refined seed oils (cottonseed oil)");
        addRule("palm oil", -2, "Refined oils",
                "Contains palm oil");

        // Artificial sweeteners
        addRule("aspartame", -3, "Artificial sweeteners",
                "Contains artificial sweeteners (aspartame)");
        addRule("sucralose", -3, "Artificial sweeteners",
                "Contains artificial sweeteners (sucralose)");
        addRule("acesulfame", -2, "Artificial sweeteners",
                "Contains artificial sweeteners (acesulfame K)");
        addRule("saccharin", -3, "Artificial sweeteners",
                "Contains artificial sweeteners (saccharin)");

        // Artificial colors
        addRule("red 40", -3, "Artificial colors",
                "Contains artificial colors (Red 40)");
        addRule("yellow 5", -3, "Artificial colors",
                "Contains artificial colors (Yellow 5)");
        addRule("yellow 6", -3, "Artificial colors",
                "Contains artificial colors (Yellow 6)");
        addRule("blue 1", -3, "Artificial colors",
                "Contains artificial colors (Blue 1)");
        addRule("blue 2", -3, "Artificial colors",
                "Contains artificial colors (Blue 2)");
        addRule("caramel color", -2, "Artificial colors",
                "Contains caramel color");

        // Preservatives
        addRule("sodium benzoate", -3, "Preservatives",
                "Contains preservatives (sodium benzoate)");
        addRule("potassium sorbate", -2, "Preservatives",
                "Contains preservatives (potassium sorbate)");
        addRule("bht", -3, "Preservatives",
                "Contains preservatives (BHT)");
        addRule("bha", -3, "Preservatives",
                "Contains preservatives (BHA)");
        addRule("sodium nitrite", -3, "Preservatives",
                "Contains nitrites");
        addRule("sodium nitrate", -3, "Preservatives",
                "Contains nitrates");

        // Flavor enhancers / gums
        addRule("monosodium glutamate", -2, "Flavor enhancers",
                "Contains flavor enhancers (MSG)");
        addRule("msg", -2, "Flavor enhancers",
                "Contains flavor enhancers (MSG)");
        addRule("artificial flavor", -2, "Flavor enhancers",
                "Contains artificial flavors");
        addRule("natural flavor", -1, "Flavor enhancers",
                "Contains vague 'natural flavors'");
        addRule("xanthan gum", -1, "Gums",
                "Contains gums/thickeners (xanthan gum)");
        addRule("carrageenan", -2, "Gums",
                "Contains gums/thickeners (carrageenan)");

        // Positives: whole foods / healthy fats
        addRule("whole grain", +3, "Whole grains",
                "Contains whole grains");
        addRule("whole oats", +3, "Whole grains",
                "Contains whole oats");
        addRule("oats", +2, "Whole grains",
                "Contains oats");
        addRule("brown rice", +2, "Whole grains",
                "Contains brown rice");
        addRule("quinoa", +3, "Whole grains",
                "Contains whole grains (quinoa)");

        addRule("olive oil", +3, "Healthy fats",
                "Uses healthier oils (olive oil)");
        addRule("avocado oil", +3, "Healthy fats",
                "Uses healthier oils (avocado oil)");
        addRule("coconut oil", +1, "Healthy fats",
                "Contains coconut oil");

        addRule("almonds", +2, "Whole foods",
                "Contains nuts (almonds)");
        addRule("cashews", +2, "Whole foods",
                "Contains nuts (cashews)");
        addRule("walnuts", +2, "Whole foods",
                "Contains nuts (walnuts)");

        // NEW: Fruits (whole fruit ingredients)
        addRule("apple", +3, "Fruits",
                "Contains whole fruit (apple)");
        addRule("apples", +3, "Fruits",
                "Contains whole fruit (apples)");
        addRule("banana", +3, "Fruits",
                "Contains whole fruit (banana)");
        addRule("bananas", +3, "Fruits",
                "Contains whole fruit (bananas)");
        addRule("strawberry", +3, "Fruits",
                "Contains whole fruit (strawberry)");
        addRule("strawberries", +3, "Fruits",
                "Contains whole fruit (strawberries)");
        addRule("blueberry", +3, "Fruits",
                "Contains whole fruit (blueberry)");
        addRule("blueberries", +3, "Fruits",
                "Contains whole fruit (blueberries)");
        addRule("raspberry", +3, "Fruits",
                "Contains whole fruit (raspberry)");
        addRule("raspberries", +3, "Fruits",
                "Contains whole fruit (raspberries)");
        addRule("blackberry", +3, "Fruits",
                "Contains whole fruit (blackberry)");
        addRule("blackberries", +3, "Fruits",
                "Contains whole fruit (blackberries)");
        addRule("grape", +2, "Fruits",
                "Contains whole fruit (grapes)");
        addRule("grapes", +2, "Fruits",
                "Contains whole fruit (grapes)");
        addRule("orange", +3, "Fruits",
                "Contains whole fruit (orange)");
        addRule("oranges", +3, "Fruits",
                "Contains whole fruit (oranges)");
        addRule("pineapple", +3, "Fruits",
                "Contains whole fruit (pineapple)");
        addRule("mango", +3, "Fruits",
                "Contains whole fruit (mango)");
        addRule("peach", +3, "Fruits",
                "Contains whole fruit (peach)");
        addRule("peaches", +3, "Fruits",
                "Contains whole fruit (peaches)");
        addRule("pear", +3, "Fruits",
                "Contains whole fruit (pear)");
        addRule("pears", +3, "Fruits",
                "Contains whole fruit (pears)");
        addRule("kiwi", +3, "Fruits",
                "Contains whole fruit (kiwi)");
        addRule("cherry", +3, "Fruits",
                "Contains whole fruit (cherry)");
        addRule("cherries", +3, "Fruits",
                "Contains whole fruit (cherries)");
        addRule("melon", +3, "Fruits",
                "Contains whole fruit (melon)");
        addRule("watermelon", +3, "Fruits",
                "Contains whole fruit (watermelon)");
        addRule("cantaloupe", +3, "Fruits",
                "Contains whole fruit (cantaloupe)");

        // NEW: Vegetables
        addRule("spinach", +3, "Vegetables",
                "Contains leafy greens (spinach)");
        addRule("kale", +3, "Vegetables",
                "Contains leafy greens (kale)");
        addRule("broccoli", +3, "Vegetables",
                "Contains vegetables (broccoli)");
        addRule("carrot", +2, "Vegetables",
                "Contains vegetables (carrot)");
        addRule("carrots", +2, "Vegetables",
                "Contains vegetables (carrots)");
        addRule("tomato", +2, "Vegetables",
                "Contains vegetables (tomato)");
        addRule("tomatoes", +2, "Vegetables",
                "Contains vegetables (tomatoes)");
        addRule("pepper", +2, "Vegetables",
                "Contains vegetables (pepper)");
        addRule("bell pepper", +2, "Vegetables",
                "Contains vegetables (bell pepper)");
        addRule("onion", +1, "Vegetables",
                "Contains vegetables (onion)");
        addRule("onions", +1, "Vegetables",
                "Contains vegetables (onions)");
        addRule("lettuce", +2, "Vegetables",
                "Contains leafy greens (lettuce)");
        addRule("cucumber", +2, "Vegetables",
                "Contains vegetables (cucumber)");
        addRule("zucchini", +2, "Vegetables",
                "Contains vegetables (zucchini)");

        // NEW: Legumes & beans
        addRule("black beans", +3, "Legumes",
                "Contains legumes (black beans)");
        addRule("kidney beans", +3, "Legumes",
                "Contains legumes (kidney beans)");
        addRule("pinto beans", +3, "Legumes",
                "Contains legumes (pinto beans)");
        addRule("chickpeas", +3, "Legumes",
                "Contains legumes (chickpeas)");
        addRule("garbanzo beans", +3, "Legumes",
                "Contains legumes (garbanzo beans)");
        addRule("lentils", +3, "Legumes",
                "Contains legumes (lentils)");
        addRule("peas", +2, "Legumes",
                "Contains legumes (peas)");

        // NEW: Seeds & extra nuts
        addRule("chia seeds", +3, "Seeds",
                "Contains seeds (chia seeds)");
        addRule("flax seeds", +3, "Seeds",
                "Contains seeds (flax seeds)");
        addRule("pumpkin seeds", +3, "Seeds",
                "Contains seeds (pumpkin seeds)");
        addRule("sunflower seeds", +2, "Seeds",
                "Contains seeds (sunflower seeds)");
        addRule("hazelnuts", +2, "Whole foods",
                "Contains nuts (hazelnuts)");
        addRule("pistachios", +2, "Whole foods",
                "Contains nuts (pistachios)");

        // NEW: Lean proteins / fish
        addRule("chicken breast", +2, "Lean protein",
                "Contains lean protein (chicken breast)");
        addRule("turkey breast", +2, "Lean protein",
                "Contains lean protein (turkey breast)");
        addRule("salmon", +3, "Lean protein",
                "Contains fatty fish (salmon)");
        addRule("tuna", +2, "Lean protein",
                "Contains fish (tuna)");
        addRule("egg", +1, "Protein",
                "Contains eggs");
        addRule("eggs", +1, "Protein",
                "Contains eggs");

        // NEW: Yogurt / fermented dairy (light positive)
        addRule("greek yogurt", +2, "Dairy",
                "Contains fermented dairy (Greek yogurt)");
        addRule("yogurt", +1, "Dairy",
                "Contains yogurt");
    }

    //Generate analysis result
    public static AnalysisResult analyze(String ingredientsText) {
        AnalysisResult result = new AnalysisResult();

        if (ingredientsText == null || ingredientsText.trim().isEmpty()) {
            result.healthScore = 0;
            result.healthLabel = "Unknown";
            result.explanation = "No ingredients provided. Unable to analyze this product.";
            return result;
        }

        //Score: 0 baseline, negative = less healthy, positive = more whole foods/healthier
        int score = 0;

        Map<String, List<String>> explanationPoints = new HashMap<>();
        Set<String> alreadyFlagged = new HashSet<>();

        //Split ingredients by comma, semicolon, or parenthesess
        String[] ingredients = ingredientsText
                .toLowerCase(Locale.ROOT)
                .split("[,;()]");

        for (String ingredient : ingredients) {
            String trimmedIngredient = ingredient.trim();
            if (trimmedIngredient.isEmpty()) continue;

            for (Rule rule : RULES) {
                //Use word boundaries to avoid matching "corn" inside "popcorn", etc.
                Pattern p = Pattern.compile("\\b" + Pattern.quote(rule.keyword) + "\\b");
                if (p.matcher(trimmedIngredient).find()) {

                    score += rule.severity;

                    //Track already flagged ingredients
                    if (!alreadyFlagged.contains(rule.keyword)) {
                        result.flaggedIngredients.add(trimmedIngredient);
                        alreadyFlagged.add(rule.keyword);
                    }

                    //Group by category
                    if (!explanationPoints.containsKey(rule.category)) {
                        explanationPoints.put(rule.category, new ArrayList<>());
                    }
                    List<String> msgs = explanationPoints.get(rule.category);
                    if (!msgs.contains(rule.message)) {
                        msgs.add(rule.message);
                    }

                    //Only add the first matching rule to simplify explanation
                    break;
                }
            }
        }

        //Final score
        result.healthScore = score;

        //Calculate heathl label
        if (score >= 5) {
            result.healthLabel = "Better choice";
        } else if (score <= -5) {
            result.healthLabel = "Less healthy";
        } else {
            result.healthLabel = "Moderation";
        }

        //Build the explanation string (Code by ChatGPT)
        StringBuilder explanationBuilder = new StringBuilder();


        explanationBuilder
                .append("Overall score: ")
                .append(score > 0 ? "+" : "")
                .append(score)
                .append(". ")
                .append("This product is categorized as \"")
                .append(result.healthLabel)
                .append("\" based on the ingredients detected.\n\n");

        if (explanationPoints.isEmpty()) {
            if (score > 0) {
                explanationBuilder.append("Mostly simple, whole-food ingredients. No major red-flag additives were detected with the current rule set.");
            } else if (score < 0) {
                explanationBuilder.append("Some potentially concerning ingredients were detected, but they could not be categorized with the current rules.");
            } else {
                explanationBuilder.append("No specific red flags or standout healthy ingredients were detected based on the current rules.");
            }
        } else {
            explanationBuilder.append("Key factors:\n\n");
            List<String> categories = new ArrayList<>(explanationPoints.keySet());
            Collections.sort(categories); // deterministic order

            for (String category : categories) {
                List<String> messages = explanationPoints.get(category);
                if (messages == null || messages.isEmpty()) continue;

                explanationBuilder.append("• ").append(category).append(":\n");
                for (String msg : messages) {
                    explanationBuilder.append("  - ").append(msg).append("\n");
                }
                explanationBuilder.append("\n");
            }
        }

        result.explanation = explanationBuilder.toString().trim();
        return result;
    }
}
